name: Update Top 5 Liked Tweets
on:
  schedule:
    - cron: '0 * * * *' # Every hour
  workflow_dispatch:

jobs:
  fetch-tweets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Set up environment
      run: echo "NOTION_SECRET=${{ secrets.NOTION_SECRET }}" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        pip install requests                
    - name: Fetch and Update Tweets
      run: python fetch_tweets.py
    - name: Commit and Push
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'github.action@github.com'
        git add .
        git commit -m "Update Liked Tweets" || echo "No changes to commit"
        git push https://${GH_TOKEN}@github.com/ajay-sreeram/blog.git HEAD:main
